name:
    title: "Forum Name"
    description: "Name of the forum."
    value: "Fourum"

url:
    title: "Forum URL"
    description: "The URL of the forum."
    value: "localhost"

email:
    title: "Admin Email"
    description: "Email address of the administrator."
    value: "example@example.com"
